#!/usr/bin/python

import sys, subprocess, os

target_file_array = []

array_size = 0

# Check if the pattern is like this and return the path if it is:
#		#       modified:   ../board/spreadtrum/sc9630/sharklj1/u-boot.lds.c
def check_and_return_filename(line):
	if line.startswith(b'#'):
		token = line.split()
		if len(token) == 3 and token[1].endswith(b':'):
			return token[2]
	return False

def modified_files_show(array):
	print('Choose which file you would like to apply \'git diff\' on:')
	for i, val in enumerate(array):
		if i < 9:
			print('\t' + int(i+1).__str__() + ')  ' + val)
		else:
			print('\t' + int(i+1).__str__() + ') ' + val)
	
	print('\t' + 'q' + ') <quit>')
	print('\t' + 'h' + ') <help>')
	try:
		user_input = raw_input('>')
	except KeyboardInterrupt:
		sys.exit()
	return user_input

def show_help():
	command = sys.argv[0].strip()
	if command.startswith('./'):
		command = command[2:]
	print(command + ": \"git status -uno\" is executed and a list of modified files, accompanied by numbers, will show up. For example:")
	print(">        1)  ../c_source_lookup/c_source_lookup.py")
	print(">        2)  ../cextension/Makefile")
	print(">        3)  ../check_sum/crc32.py")
	print(">        4)  gd")
	print(">        q)")
	print(">        h) ")
	print(">    Type '1' to show the diff of ../c_source_lookup/c_source_lookup.py.")
	print(">    Type 'v1' to show the diff of ../c_source_lookup/c_source_lookup.py by vimdiff.")
	print(">    Type 'm1' to show the diff of ../c_source_lookup/c_source_lookup.py by meld.")
	print("")


if len(sys.argv) != 1:
	print("Donot pass argument!")
	sys.exit()

if os.system('git rev-parse') != 0:
	sys.exit()

p1=subprocess.Popen(['/bin/sh', '-c', 'git status -uno'], stdout=subprocess.PIPE)

gitoutput= p1.stdout.read()
gitoutputlines = gitoutput.splitlines()

not_staged = 0
for i, val in enumerate(gitoutputlines):
	val_str = val.decode("utf-8")
	if 'Changes not staged for commit' in val_str:
		not_staged = 1
	if not_staged == 1:
		target_file = check_and_return_filename(val)
		if target_file != False:
			target_file_array.append(target_file)

array_size = len(target_file_array)

if array_size == 0:
	print("No modified file. Quit!")
	sys.exit()

while True:
	user_input = modified_files_show(target_file_array)
	
	if user_input == 'h' or user_input == 'H':
		show_help()
		continue

	if user_input == 'q' or user_input == 'Q':
		sys.exit()
	
	try:
		vimdiff = 0
		meld = 0

		if user_input.startswith('v'):
			vimdiff = 1
			user_input = user_input[1:]
		elif user_input.startswith('m'):
			meld = 1
			user_input = user_input[1:]
		int_user_input = int(user_input)
		int_user_input = int_user_input - 1
		if int_user_input < len(target_file_array) and int_user_input >=0:
			if vimdiff == 1:
				os.system("git difftool -t vimdiff " + target_file_array[int_user_input])
			elif meld == 1:
				os.system("meld " + target_file_array[int_user_input])
			else:
				os.system("git diff " + target_file_array[int_user_input])
	except ValueError:
		print("Wrong key-in. Try again!")
	except:
		pass







